# -*- coding: utf-8 -*-
"""Test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12F2F43-iVNvdjg04jyo5PykfmBQvWXIB
"""

!pip install anthropic

import anthropic
client = anthropic.Anthropic(api_key="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")  # Your key

message = client.messages.create(
    model="claude-sonnet-4-5",  # Current Sonnet (Feb 2026 standard)
    max_tokens=500,
    messages=[{"role": "user", "content": """
FactSet sample vs MSCI World:
Tech: 25% fund (20% BM), 15% ret (12% BM)
Energy: 8% fund (10% BM), 5% ret (7% BM)
Brinson effects? Simple explanation + client bullets.
    """}]
)
print(message.content[0].text)

